# Generated by Django 3.2.8 on 2021-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_alter_houseimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
